// Generated by CoffeeScript 1.10.0
(function() {
  var base, io;

  (base = process.env).PORT || (base.PORT = 3000);

  io = require('socket.io').listen(process.env.PORT);

  console.log("socket.io server start - port: " + process.env.PORT);

  io.sockets.on('connection', function(socket) {
    var user;
    user = socket.handshake.query.user;
    socket.emit('chat', {
      msg: 'hello world (from server)'
    });
    return socket.on('chat', function(data) {
      console.log(data);
      data.user = user;
      return io.sockets.emit('chat', data);
    });
  });

  if (process.env.EXIT_AT) {
    setTimeout(function() {
      return process.exit();
    }, process.env.EXIT_AT - 0);
  }

}).call(this);
